name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # todo: calculate matrix automatically
      # todo: derive ghc version from plan
      matrix:
        plans:
          - plan: ghc-8.10.7
            ghc-version: 8.10.7
          - plan: ghc-9.0.2
            ghc-version: 9.0.2
          - plan: ghc-9.2.4
            ghc-version: 9.2.4
          - plan: ghc-9.2.5
            ghc-version: 9.2.5
          - plan: ghc-9.4.4
            ghc-version: 9.4.4
          - plan: stackage-nightly
            ghc-version: 9.4.4

    steps:
    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.plans.ghc-version }}

    - name: cache cabal store
      uses: actions/cache@v3
      with:
        key: cabal-store-${{ runner.os }}-${{ matrix.plans.plan }}-${{ github.sha }}
        path: ~/.cabal/store
        restore-keys: cabal-store-${{ runner.os }}-${{ matrix.plans.plan }}-

    - run: cabal build --ghc-options -Werror --project-file "ci-configs/${{ matrix.plans.plan }}.config"

    - run: mv dist-newstyle/cache/plan.json plan-${{ matrix.plans.plan }}.json

    - name: Upload build plan as artifact
      uses: actions/upload-artifact@v3
      with:
        name: plans
        path: plan-${{ matrix.plans.plan }}.json


  static:
    name: build static binary
    runs-on: ubuntu-latest
    container: alpine:3.12
    steps:
    - name: Install system dependencies
      run: |
        apk add --no-cache curl gcc g++ gmp-dev ncurses-dev libffi-dev make xz gzip tar perl git bash sudo binutils-gold
        apk add --no-cache zlib zlib-dev zlib-static gmp gmp-dev ncurses-static
        apk add --no-cache file

    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.4.4'

    - name: cache cabal store
      uses: actions/cache@v3
      with:
        key: cabal-store-alpine-${{ github.sha }}
        path: ~/.cabal/store
        restore-keys: cabal-store-alpine-

    - name: Checkout code
      uses: actions/checkout@v3

    # cannot use cabal install, https://github.com/haskell/cabal/issues/7297
    - name: Build
      run: cabal build --enable-executable-static

    - run: mv dist-newstyle/build/*/*/cabal-plan-bounds-*/x/cabal-plan-bounds/build/cabal-plan-bounds/cabal-plan-bounds .

    - name: Strip
      run: strip cabal-plan-bounds

    - name: File information
      run: ls -sh cabal-plan-bounds; file cabal-plan-bounds

    - name: Gzip and rename
      run: gzip -S .linux.gz cabal-plan-bounds; ls -sh *.gz

    - uses: actions/upload-artifact@v3
      with:
        name: static-build
        path: cabal-plan-bounds.linux.gz

  bounds:
    runs-on: ubuntu-latest
    name: Calculate cabal bounds
    needs:
    - static
    - build
    steps:
    - uses: actions/checkout@v3

    - name: Fetch static build
      uses: actions/download-artifact@v3
      with:
        name: static-build
        path: static-build

    - run: gunzip static-build/cabal-plan-bounds.linux.gz
    - run: chmod +x static-build/cabal-plan-bounds.linux

    - name: Load plans
      uses: actions/download-artifact@v3
      with:
        name: plans
        path: plans

    - run: find plans/

    - run: ./static-build/cabal-plan-bounds.linux plans/*.json -c cabal-plan-bounds.cabal

    - run: git diff cabal-plan-bounds.cabal
    - name: Fail if .cabal file was changed
      run: git diff-files --quiet cabal-plan-bounds.cabal|| exit 1

  release:
    name: Release binary
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs:
    - bounds
    steps:
    - name: Fetch static build
      uses: actions/download-artifact@v3
      with:
        name: static-build
        path: static-build
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: static-build/cabal-plan-bounds.linux.gz
